### ISSUE TITLE
home page

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-nicole-deltoro/geekwise-wordpress#17]
what happened to your home page?

![screen shot 2016-06-10 at 9 45 38 am](https://cloud.githubusercontent.com/assets/7436666/15971866/2d1faafc-2ef0-11e6-90a2-0a020a4c79a2.png)

**Comment by geekwise-nicole-deltoro** [comment]
![image](https://cloud.githubusercontent.com/assets/17086865/15972313/99527fea-2ef2-11e6-9325-6278a165a398.png)

THIS IS MY HOME PAGE

**Comment by geekwise-nicole-deltoro** [comment]
done

**Comment by Sramos9191** [comment]
why does a different home page show up when you go to the website? what happened to that page?

**Comment by geekwise-nicole-deltoro** [comment]
i dont know what you are talking about 
can you show me the page

**Comment by Sramos9191** [comment]
your home page should appear when you type in "geekwise-wordpress-geekwise77.c9users.io" what happened to the home page there? 

why does it look like this?:
![screen shot 2016-06-10 at 9 45 38 am](https://cloud.githubusercontent.com/assets/7436666/15973752/e9ee2f10-2ef9-11e6-94b5-b6213977dfc7.png)

**Comment by geekwise-nicole-deltoro** [comment]
now try it

**Comment by geekwise-nicole-deltoro** [comment]
done
