### ISSUE TITLE
contact - icon - link

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-nicole-deltoro/geekwise-wordpress#18]
the geekwise logo should link to your homepage and not the geekwise website homepage

![screen shot 2016-06-10 at 10 45 48 am](https://cloud.githubusercontent.com/assets/7436666/15973487/8ab73d8a-2ef8-11e6-87a7-0d823463562e.png)

**Comment by geekwise-nicole-deltoro** [comment]
i dont know why the website is acting funny but here is my link 
https://geekwise-wordpress-geekwise77.c9users.io/home/

**Comment by geekwise-nicole-deltoro** [comment]
it links on my site

**Comment by Sramos9191** [comment]
on the contact page

**Comment by geekwise-nicole-deltoro** [comment]
done
