### ISSUE TITLE
cohort - member description

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-nicole-deltoro/geekwise-wordpress#24]
the font in the description box should be smaller and not bold, to match the original site. See below.

original site:
![screen shot 2016-06-13 at 8 44 55 am](https://cloud.githubusercontent.com/assets/7436666/16013718/614310ee-3143-11e6-93f1-806921c32c2c.png)

your site:
![screen shot 2016-06-13 at 8 44 42 am](https://cloud.githubusercontent.com/assets/7436666/16013719/61446cbe-3143-11e6-88e6-f74afab2f60a.png)

**Comment by geekwise-nicole-deltoro** [comment]
done
