### ISSUE TITLE
home - navigational links

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-nicole-deltoro/geekwise-wordpress#3]
center the links inside of the navigation so they're not so close to the top

**Comment by geekwise-nicole-deltoro** [comment]
done

**Comment by Sramos9191** [comment]
@geekwise-nicole-deltoro can you move them up a little so they're centered instead of too close to the top and too close to the bottom (you'll notice it the most when you hover over it)

**Comment by Sramos9191** [comment]
@geekwise-nicole-deltoro 
![screen shot 2016-06-02 at 4 28 53 pm](https://cloud.githubusercontent.com/assets/7436666/15764363/3015a99e-28df-11e6-98ed-2205d4abbad9.png)

**Comment by geekwise-nicole-deltoro** [comment]
done
