### ISSUE TITLE
about - content

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-nicole-deltoro/geekwise-wordpress#6]
the main content of the page needs to be styled to match the geekwise website

yours:
![screen shot 2016-05-27 at 11 38 42 am](https://cloud.githubusercontent.com/assets/7436666/15617875/b24a0e6c-23ff-11e6-9ee2-ed1e85077608.png)

theirs:
![screen shot 2016-05-27 at 11 38 52 am](https://cloud.githubusercontent.com/assets/7436666/15617876/b25049da-23ff-11e6-84c4-4996d52025b2.png)

**Comment by geekwise-nicole-deltoro** [comment]
done
